colors:
  primary:
    background: "#1e1e1e"
    foreground: "#d4d4d4"

  normal:
    black: "#666666"
    red: "#ef8171"
    green: "#e5f779"
    yellow: "#fff796"
    blue: "#4186be"
    magenta: "#ef9ebe"
    cyan: "#71bebe"
    white: "#ffffff"

  bright:
    black: "#666666"
    red: "#ef8171"
    green: "#e5f779"
    yellow: "#fff796"
    blue: "#4186be"
    magenta: "#ef9ebe"
    cyan: "#71bebe"
    white: "#ffffff"

  dim:
    black: "#131415"
    red: "#864343"
    green: "#777c44"
    yellow: "#9e824c"
    blue: "#556a7d"
    magenta: "#75617b"
    cyan: "#5b7d78"
    white: "#828482"
